### PR TITLE
Feature/gt 134 trash spawn and pickup

### PR DESCRIPTION
**Pull request by logoffro1**
All the text from before, added some stuff I forgot to push

### CODE REVIEW

**Review by dbecu — COMMENTED** [review]
Looks really good! Love it when you dispose of the trash. I scanned through your code quickly and I have no comments there 👍
However, I do have a few general remarks: 

- Could you make the hitbox of the trash bigger? Having to aim accurately at such a small item can get a bit frustrating. 
- Would it be possible for the trash to get spawned in where the player is not looking? Just so that the player doesnt have to know when trash gets spawned.
- Can trash picking move the progress bar? Even by just a little bit?
- I'm not sure if this happens, but if the trash falls in the canal, does it fall out of the world forever? Because if it does, might be good to make sure it's destroyed at some limit
- Can you set the speed of the trash spawning easily? I saw there's a limit, but not nesessarily a speed. I think it might be useful to be able to change that manually, so that for harder missions, the speed can be faster. And even during one mission, it can get faster. Although I'm not too sure about this idea..

Sorry for the mountain of remarks. These are just things that popped in my mind, feel free to disagree

**Comment by logoffro1** [comment]
> 
Thank you for your feedback!

I have pushed a new version:
The changes:

- I made the hitboxes for trash a bit bigger
- The idea of this code is for all the trash to be generated at the start of the round, and the reason why the player sees it happening is because for testing purposes I'm spawning so many objects that it takes them a while, but with a more realistic spawn rate it wouldn't be noticeable. (But for the future once we add NPCs, I will make it such the trash gets spawned during the round, because the NPCs would leave trash behind)
- Now the sustainability bar increases once you empty your bag
- Now the trash gets destroyed if it falls out of the map
- I can set a speed for spawning, but for right now I don't think it's necessary (because we might change how we spawn the trash in the future)

**Comment by dbecu** [comment]
Great, thank you! Looks good, I think it can be merged now

**Comment by egecnr** [comment]
Double checked it. Now everything is  perfect 👍   Lets merge it so that I can pull it to the branches I work and play with it when i get bored

**Pull request merged**
