### PR TITLE
Feature/gt 255 info popup

### PR DESCRIPTION
**Pull request by dbecu**
Popup after mimigame to show a fun sustainability fact
At beginning of minigame, there is a brief instruction on how to play it

### CODE REVIEW

**Comment by omaralawin** [comment]
Looks great! Just a few comments though.
-an achievement popup comes up for a moment after completing a task, not sure if this is intended
- the popup is a little bit too low, its near the center of the screen,
- the popup does not disappear for me until a new one comes up, then it replaces the existing one
- the colour beep minigame says to press space
- i dont know if this is a problem from this branch but the recycle/wind turbine minigame are not there strangely enough.

**Comment by omaralawin** [comment]
image

**Comment by omaralawin** [comment]
oh yeah, one last thing, it might be better to disable the helpful thing at the start of each minigame after the first time for that minigame.

**Comment by egecnr** [comment]
I love the info popup that comes right after the mini game success text! Its very nice looking, gives an achievement vibe and I found it refreshing to have. 

However, the instruction fade away functionality has its downs. I did not have problems with any mini games whereas I failed a color beep because I missed the first beep while reading so I think we need 3s wait time while the instructions are fading away.

Other than the point above, marvelous work! Good job

**Pull request merged**
